### ISSUE TITLE
curl_multi_add_handle - The given object is not a valid coroutine CurlMultiHandle object

### ISSUE THREAD

**Issue by Gemorroj** [swoole/swoole-src#4522]
1. What did you do? If possible, provide a simple script for reproducing the error.
I try to send http requests using `symfony/http-client` and https://github.com/php-runtime/swoole
Here an example project https://github.com/Gemorroj/test-swoole-symfony

2. What did you expect to see?
parallel work

3. What did you see instead?
```
php_1  | Fatal error: Uncaught Swoole\Error: The given object is not a valid coroutine CurlMultiHandle object in /var/www/app/vendor/symfony/http-client/Response/CurlResponse.php:176
php_1  | Stack trace:
php_1  | #0 /var/www/app/vendor/symfony/http-client/Response/CurlResponse.php(176): curl_multi_add_handle(Object(CurlMultiHandle), Object(CurlHandle))
php_1  | #1 /var/www/app/vendor/symfony/http-client/CurlHttpClient.php(318): Symfony\Component\HttpClient\Response\CurlResponse->__construct(Object(Symfony\Component\HttpClient\Internal\CurlClientState), Object(CurlHandle), Array, NULL, 'GET', Object(Closure), 479232)
php_1  | #2 /var/www/app/vendor/symfony/http-client/ScopingHttpClient.php(93): Symfony\Component\HttpClient\CurlHttpClient->request('GET', 'https://httpbin...', Array)
php_1  | #3 /var/www/app/src/Controller/TestController.php(134): Symfony\Component\HttpClient\ScopingHttpClient->request('GET', 'https://httpbin...')
php_1  | #4 @swoole-src/library/core/Coroutine/functions.php(37): App\Controller\TestController::App\Controller\{closure}()
php_1  | #5 {main}
php_1  |   thrown in /var/www/app/vendor/symfony/http-client/Response/CurlResponse.php on line 176
```

4. What version of Swoole are you using (show your `php --ri swoole`)?
master
```
/var/www/app # php --ri swoole

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.9.0-dev
Built => Dec  4 2021 17:52:01
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1l  24 Aug 2021
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
zlib => 1.2.11
brotli => E16777225/D16777225
mutex_timedlock => enabled
pthread_barrier => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
it's docker-win (Host - Win10x64, Conatainer - Alpine Linux 3.15)
data from container:
```
Linux e03e07c18a69 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 Linux

PHP 8.0.13 (cli) (built: Nov 30 2021 07:57:55) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.13, Copyright (c) Zend Technologies

gcc: not found
```

**Comment by slotkeonline** [comment]
Just to inform You, I'm facing the same issue. I was trying to add Sentry support for my project and the same thing happen.
`PHP Fatal error:  Uncaught Swoole\Error: The given object is not a valid coroutine CurlMultiHandle object in /app/vendor/symfony/http-client/Response/CurlResponse.php:177
Stack trace:
#0 /app/vendor/symfony/http-client/Response/CurlResponse.php(177): curl_multi_add_handle()
`
The version I've used is 4.8.7 on PHP 8.1

**Comment by matyhtf** [comment]
The latest version has been fixed

**Comment by Gemorroj** [comment]
@matyhtf problem still exists. I have tested on 4.8.x and mater branches

**Comment by Jeckerson** [comment]
Sentry uses curl and each instance of curl request must be inside same coroutine. The initialisation of `Sentry\init()` must be or inside each coroutine or each request, but this approach will cause **memory leaks**.

One of possible solutions that I found is to init Sentry and capture any type of error: warning or exception via `set_error_handler()`, here is code example:
```php
set_error_handler(function ($severity, $message, $file, $line) {
    init(['dsn' => $_ENV['SENTRY_DSN']]);
    captureException(new ErrorException($message, 0, $severity, $file, $line));
});
```

And full code example with Swoole's HTTP server:
```php
<?php

declare(strict_types=1);

require_once 'vendor/autoload.php';

if (isset($_ENV['SENTRY_DSN'])) {
    set_error_handler(function ($severity, $message, $file, $line) {
        init(['dsn' => $_ENV['SENTRY_DSN']]);
        captureException(new ErrorException($message, 0, $severity, $file, $line));
    });
}

$server = new Server('0.0.0.0', 9501);
$server->on('start', function () {
    echo "Swoole http server is started\n";
});
$server->on('request', function (Request $request, Response $response) use ($app) {
    $test = [];
    var_dump($test[1]); // Warning error
    throw new \RuntimeException('Sentry test'); // Exception error

    $response->end('Hello world');
});
$server->start();
```
